name: almufeed
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: ^2.0.5

  sms_autofill: ^2.3.0

  sms_otp_auto_verify: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"
flutter_icons:
      android: "launcher_icon"
      ios: true
      image_path: "assets/image/almlogopng.png"


flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf
        - asset: assets/fonts/montserrat_semibold.ttf
        - asset: assets/fonts/montserrat_regular.ttf

  assets:
    - assets/image/
